version: '3'

services:
  etcd:
    image: bitnami/etcd:3.4.15
    container_name: chat-etcd
    ports:
      - "3379:2379"
      - "3380:2380"
    environment:
      - ETCD_ENABLE_V2=true
      - ALLOW_NONE_AUTHENTICATION=yes
      # 这里需要换成自己的本地网络ip
      - ETCD_ADVERTISE_CLIENT_URLS=http://192.168.50.8:3379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_NAME=etcd
    volumes:
      - ./components/etcd/data:/bitnami/etcd/data
      - ./components/etcd/logs:/bitnami/etcd/logs
    networks:
      easy-chat:

  redis:
    image: redis:alpine3.18
    ports:
      - 16379:6379
    container_name: chat-redis
    volumes:
      - ./components/redis/data:/data
      - ./components/redis/config/redis.conf:/usr/local/redis/config/redis.conf
    environment:
      TZ: Asia/Shanghai
    restart: always
    networks:
      easy-chat:
    command: redis-server --requirepass easy-chat --appendonly yes

  mysql:
    # 我这里是 mac m4 架构，所以使用的是 mysql-server 镜像
    image: mysql/mysql-server:5.7
    ports:
      - 13306:3306
    container_name: chat-mysql
    volumes:
      - ./components/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: easy-chat
    restart: always
    networks:
      easy-chat:

networks:
  easy-chat:
    driver: bridge
