// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type User struct {
	Id       string `json:"id"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Sex      byte   `json:"sex"`
	Avatar   string `json:"avatar"`
}
